### PR TITLE
Uninstall the repl ring event handler on shutdown

### PR DESCRIPTION
**Pull request by Vagabond**
This avoids crashes if the ring changes after repl has stopped.

### CODE REVIEW

**Comment by bookshelfdave** [comment]
My first run of replication2 failed with this error:

```
09:13:50.512 [warning] replication2 failed: {{badmatch,undefined},[{replication2,pb_write_during_shutdown,3,[{file,"tests/replication2.erl"},{line,441}]},{replication2,replication,3,[{file,"tests/replication2.erl"},{line,433}]},{replication2,confirm,0,[{file,"tests/replication2.erl"},{line,44}]}]}
09:13:50.512 [error] Error in process <0.99.0> on node 'riak_test@127.0.0.1' with exit value: {{badmatch,undefined},[{replication2,pb_write_during_shutdown,3,[{file,"tests/replication2.erl"},{line,441}]},{replication2,replication,3,[{file,"tests/replication2.erl"},{line,433}]},{replication2,confirm,0,
```

**Comment by Vagabond** [comment]
That line is:

``` erlang
 {ok, Port} = rpc:call(Target, application, get_env, [riak_api, pb_port]),
```

Which hardly seems relevant.

**Comment by bookshelfdave** [comment]
hm, maybe just something with my setup. I'll build from scratch and rerun.

**Comment by bookshelfdave** [comment]
+1, wfm now with a clean build.

**Pull request merged**
