### PR TITLE
Fix source/sink typo.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Correct the source/sink typo that exists in the stats.

Addresses https://github.com/basho/riak_repl/issues/397.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@joedevivo force pushed update.

**Comment by joedevivo** [comment]
+1 all tests pass, I am confident that these stats can be jsonified

**Comment by cmeiklejohn** [comment]
YOLO

**Comment by joedevivo** [comment]
+1 a5305ec

**Comment by cmeiklejohn** [comment]
@borshop merge

**Comment by cmeiklejohn** [comment]
Whoa, did borshop just delete this without merging?

**Comment by cmeiklejohn** [comment]
@reiddraper @Vagabond @jaredmorrow Did I just get trolled?  I got a close and delete without merge?

**Comment by Vagabond** [comment]
I see it merged to develop, don't you?

**Comment by cmeiklejohn** [comment]
Ah, yeah, I do.  Thanks.

**Pull request closed without merging**
