### PR TITLE
Refactored RTQ to ignore exceptions from pull delivery functions. [JIRA: RIAK-2425]

### PR DESCRIPTION
**Pull request by jonmeredith**
...and improved the error if the consumer is not registered to
include information needed to debug it.

Added to help #652 (RIAK-1476) get merged through bors.

### CODE REVIEW

**Comment by jonmeredith** [comment]
create jira issue

**Comment by bsparrow435** [comment]
:+1: 5e6e0342808bfda8467316afb474a14202f0c140

**Comment by jonmeredith** [comment]
I beg to differ Mr Borshop

```
./rebar eunit skip_deps=true
==> riak_repl (eunit)
OK, passed 5 tests

35% {rt_source_eqc,disconnect,1}
26% {rt_source_eqc,connect_to_v1,2}
21% {rt_source_eqc,push_object,3}
19% {rt_source_eqc,connect_to_v2,2}
....................................................................................................(x10)...............
OK, passed 250 tests

42.68% {riak_repl2_rtq_eqc,push,2}
42.16% {riak_repl2_rtq_eqc,push,3}
9.55% {riak_repl2_rtq_eqc,reregister_consumer,2}
5.61% {riak_repl2_rtq_eqc,test_init,1}
....................................................................................................(x10)...............
OK, passed 250 tests
....................................................................................................(x10)....................................................................................................(x100)..................................................................................(x10)....(x1)....
Time limit reached: 30.0 seconds.

OK, passed 9344 tests

6.993% {initiating_connection,{riak_core_cluster_conn_eqc,poll_cluster,1}}
6.915% {initiating_connection,{riak_core_cluster_conn_eqc,garbage_event,1}}
6.852% {initiating_connection,{riak_core_cluster_conn_eqc,send_timeout,1}}
6.746% {initiating_connection,{riak_core_cluster_conn,status,1}}
5.970% {waiting_for_cluster_name,{riak_core_cluster_conn_eqc,cluster_name,1}}
5.842% {waiting_for_cluster_name,{riak_core_cluster_conn_eqc,poll_cluster,1}}
5.841% {waiting_for_cluster_name,{riak_core_cluster_conn_eqc,garbage_event,1}}
5.752% {waiting_for_cluster_name,{riak_core_cluster_conn,status,1}}
5.425% {connecting,{riak_core_cluster_conn_eqc,garbage_event,1}}
5.414% {connecting,{riak_core_cluster_conn_eqc,poll_cluster,1}}
5.388% {connecting,{riak_core_cluster_conn_eqc,connected_to_remote,1}}
5.375% {connecting,{riak_core_cluster_conn,status,1}}
4.825% {waiting_for_cluster_members,
           {riak_core_cluster_conn_eqc,garbage_event,1}}
4.798% {waiting_for_cluster_members,
           {riak_core_cluster_conn_eqc,poll_cluster,1}}
4.752% {waiting_for_cluster_members,
           {riak_core_cluster_conn_eqc,cluster_members,1}}
4.719% {waiting_for_cluster_members,{riak_core_cluster_conn,status,1}}
2.113% {connected,{riak_core_cluster_conn,status,1}}
2.099% {connected,{riak_core_cluster_conn_eqc,garbage_event,1}}
2.094% {connected,{riak_core_cluster_conn,stop,1}}
2.088% {connected,{riak_core_cluster_conn_eqc,poll_cluster,1}}
  All 192 tests passed.
Cover analysis: /private/tmp/riak_repl/.eunit/index.html
```

**Comment by jonmeredith** [comment]
The error on the builder looks timeout related

```
............................................................................................Failed! After 93 tests.
[{set,{var,1},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,2},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,3},{call,riak_core_cluster_conn_eqc,send_timeout,[{var,fsm_pid}]}},
 {set,{var,4},{call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,5},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,6},
      {call,riak_core_cluster_conn_eqc,connected_to_remote,[{var,fsm_pid}]}},
 {set,{var,7},{call,riak_core_cluster_conn_eqc,cluster_name,[{var,fsm_pid}]}},
 {set,{var,8},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,9},
      {call,riak_core_cluster_conn_eqc,cluster_members,[{var,fsm_pid}]}},
 {set,{var,10},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,11},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,12},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,13},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,14},{call,riak_core_cluster_conn,stop,[{var,fsm_pid}]}}]
test/riak_core_cluster_conn_eqc.erl:104:<0.2189.0>: 
Cmds: [{initiating_connection,{riak_core_cluster_conn_eqc,poll_cluster,1}},
       {initiating_connection,{riak_core_cluster_conn,status,1}},
       {initiating_connection,{riak_core_cluster_conn_eqc,send_timeout,1}},
       {connecting,{riak_core_cluster_conn_eqc,garbage_event,1}}]

test/riak_core_cluster_conn_eqc.erl:107:<0.2189.0>: 
Result: {postcondition,
            {'EXIT',
                {timeout,
                    {gen_fsm,sync_send_all_state_event,
                        [<0.2651.0>,current_state]}}}}

test/riak_core_cluster_conn_eqc.erl:108:<0.2189.0>: 
History: [{eqc_statem_history,
              {initiating_connection,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn_eqc,poll_cluster,[<0.2651.0>]},
              [],
              {normal,ok}},
          {eqc_statem_history,
              {initiating_connection,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn,status,[<0.2651.0>]},
              [],
              {normal,{initiating_connection,"FARFARAWAY"}}},
          {eqc_statem_history,
              {initiating_connection,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn_eqc,send_timeout,[<0.2651.0>]},
              [],
              {normal,ok}},
          {eqc_statem_history,
              {connecting,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn_eqc,garbage_event,[<0.2651.0>]},
              [],
              {normal,ok}}]

ok /= {postcondition,
          {'EXIT',
              {timeout,
                  {gen_fsm,sync_send_all_state_event,
                      [<0.2651.0>,current_state]}}}}
Shrinking xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(0 times)
[{set,{var,1},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,2},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,3},{call,riak_core_cluster_conn_eqc,send_timeout,[{var,fsm_pid}]}},
 {set,{var,4},{call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,5},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,6},
      {call,riak_core_cluster_conn_eqc,connected_to_remote,[{var,fsm_pid}]}},
 {set,{var,7},{call,riak_core_cluster_conn_eqc,cluster_name,[{var,fsm_pid}]}},
 {set,{var,8},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,9},
      {call,riak_core_cluster_conn_eqc,cluster_members,[{var,fsm_pid}]}},
 {set,{var,10},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,11},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,12},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,13},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,14},{call,riak_core_cluster_conn,stop,[{var,fsm_pid}]}}]
test/riak_core_cluster_conn_eqc.erl:104:<0.2189.0>: 
Cmds: [{initiating_connection,{riak_core_cluster_conn_eqc,poll_cluster,1}},
       {initiating_connection,{riak_core_cluster_conn,status,1}},
       {initiating_connection,{riak_core_cluster_conn_eqc,send_timeout,1}},
       {connecting,{riak_core_cluster_conn_eqc,garbage_event,1}}]

test/riak_core_cluster_conn_eqc.erl:107:<0.2189.0>: 
Result: {postcondition,
            {'EXIT',
                {timeout,
                    {gen_fsm,sync_send_all_state_event,
                        [<0.2651.0>,current_state]}}}}

test/riak_core_cluster_conn_eqc.erl:108:<0.2189.0>: 
History: [{eqc_statem_history,
              {initiating_connection,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn_eqc,poll_cluster,[<0.2651.0>]},
              [],
              {normal,ok}},
          {eqc_statem_history,
              {initiating_connection,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn,status,[<0.2651.0>]},
              [],
              {normal,{initiating_connection,"FARFARAWAY"}}},
          {eqc_statem_history,
              {initiating_connection,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn_eqc,send_timeout,[<0.2651.0>]},
              [],
              {normal,ok}},
          {eqc_statem_history,
              {connecting,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn_eqc,garbage_event,[<0.2651.0>]},
              [],
              {normal,ok}}]

ok /= {postcondition,
          {'EXIT',
              {timeout,
                  {gen_fsm,sync_send_all_state_event,
                      [<0.2651.0>,current_state]}}}}
riak_core_cluster_conn_eqc:74: eqc_test_...*failed*
in function riak_core_cluster_conn_eqc:'-eqc_test_/0-fun-3-'/1 (test/riak_core_cluster_conn_eqc.erl, line 74)
**error:{assertEqual_failed,[{module,riak_core_cluster_conn_eqc},
                     {line,74},
                     {expression,"eqc : quickcheck ( eqc : testing_time ( 30 , ? QC_OUT ( prop_cluster_conn_state_transition ( ) ) ) )"},
                     {expected,true},
                     {value,false}]}
  output:<<"Starting Quviq QuickCheck version 1.36.1
   (compiled at {{2015,9,11},{11,37,51}})
Licence for Basho (Continuous Integration) reserved until {{2016,3,1},
                                                           {17,31,34}}
```

**Pull request merged**
