### PR TITLE
Add callback annotations to gen_leader.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Stop ignoring the error, and provide a set of callback annotations for
the gen_leader module.

Addresses #553.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@seancribbs mind a review when you have a second?

**Comment by seancribbs** [comment]
Dialyzer is still clean, so other than the documentation issue, I give the thumbs up.

**Comment by cmeiklejohn** [comment]
Adding documentation now.

**Comment by cmeiklejohn** [comment]
Pushed 49a10ec to address.  If this looks good, since this is a bors managed repo, remember to :1 the commit SHA.

**Comment by Vagabond** [comment]
What is wrong with the sys:handle_debug stuff? I guess we don't care since we don't use that.

**Comment by cmeiklejohn** [comment]
I think the major issue was that it's no longer spec'd the way we use it.

**Comment by cmeiklejohn** [comment]
I'm merging giving @seancribbs's :+1: and that the handle_debug stuff existed outside of this change set.

**Comment by seancribbs** [comment]
:+1: 49a10ec

**Comment by cmeiklejohn** [comment]
@borshop merge

**Comment by cmeiklejohn** [comment]
@borshop merge.

**Pull request merged**
