### PR TITLE
Fix riak_repl2_rtq_eqc test cleanup

### PR DESCRIPTION
**Pull request by nickelization**
Leaving the rtq_max_bytes setting as-is could sometimes clobber other
tests that didn't expect random values to be present in that setting.
(Specifically the riak_repl2_rtsource_conn test, in the example we found
on the builder.)

Unsetting this value on cleanup fixes the problem.

### CODE REVIEW

**Comment by JeetKunDoug** [comment]
:+1: 573bfa6

**Comment by JeetKunDoug** [comment]
@borshop: retry

**Comment by JeetKunDoug** [comment]
Re-kicked the build manually on Buildbot, but it failed to properly update status here - so asking @borshop nicely to retry.

**Comment by nickelization** [comment]
After discussing with @JeetKunDoug and @jonmeredith, decided to manually merge this fix. It sucks to have to bypass bors, but the fix is just for a test, and so the fact that other tests are still broken shouldn't stop us from at least partially improving the situation.

**Pull request merged**
