### PR TITLE
Added send and recv sum kpbs stats for rt and fs

### PR DESCRIPTION
**Pull request by lordnull**
fullsync_send_kpbs, fullsync_recv_kbps, realtime_send_kbps, and
realtime_recv_kbps are at the top level of both console and web json
stats.

fullsync stats are only useful while a fullsync is in progress; due to the
connect/disconnect nature of fullsync, it will vary widely.

### CODE REVIEW

**Comment by bookshelfdave** [comment]
I rebased this branch against 1.3 in mw-anya-stat-patch-rebased

**Comment by bookshelfdave** [comment]
with the rebased branch `mw-anya-stat-patch-rebased`, the stats work fine. Since these numbers can change quickly, it might make sense to (also?) keep a histogram, although I'm not sure if we should try to cram that into 1.3.2. 

@lordnull if you open a PR with `mw-anya-stat-patch-rebased`, I'll +1 and merge it.

**Comment by jonmeredith** [comment]
The intent for this was to graph on a stats system, so the trend can go there.  Post-1.4 I think we need to reconsider how TCP mon reports this info - we're going to have more connections going through it once we move handoff/aae and possibly bulk vnodes on to it.

We'll probably need to split it into two parts - one that keeps track of open connections and octets/packets sent.  Another that worries about keeping around mini-throughput rates for commandline tools.  The heavy lifting for big clusters is going to get done by the monitoring systems, but when it all goes to crap, having that built in is very useful.

**Comment by lordnull** [comment]
Look to https://github.com/basho/riak_repl/pull/274 for the merge, as it has been rebased (by @dave) and can do so cleanly. I'm going to close this / reference it in the other.

**Pull request closed without merging**
