### PR TITLE
moved gen_server2 to riak_repl

### PR DESCRIPTION
**Pull request by bookshelfdave**
see https://github.com/basho/riak_core/pull/407
### Testing
- [ ] manual verification of code
- [ ] eunit
- [ ] EQC
- [ ] riak_test
- [ ] Dialyzer
- [ ] XRef
- [ ] Coverage reports
### Documentation
- [ ] internal docs (repl wiki)

### CODE REVIEW

**Comment by lordnull** [comment]
While grep'ing through the code base and looking the modules that acutally use riak_core_gen_server, it doesn't look like we actually use any of the alterations. So, this will be needed in the short term, we should look into removing riak_core_gen_server use in future refactoring.

**Comment by slfritchie** [comment]
Howdy.  What's the status of this PR?  It appears to be blocking https://github.com/basho/riak_core/pull/407

**Comment by bookshelfdave** [comment]
@slfritchie is basho/riak_core#407 required for 2.0? if not, I'd say kick the issue over the fence so we can work on higher priority issues until code freeze.

**Comment by cmeiklejohn** [comment]
Moving to 2.1.

**Comment by Vagabond** [comment]
We should just switch back to regular gen_server.

**Comment by cmeiklejohn** [comment]
Yeah, agree.

**Comment by Vagabond** [comment]
Closing in favor of #570

**Pull request closed without merging**
