### PR TITLE
Add support for n_val and sloppy_quorum

### PR DESCRIPTION
**Pull request by slfritchie**
... to mirror the riak_kv repo's implementation of same.

### CODE REVIEW

**Comment by buddhisthead** [comment]
@slfritchie Does this PR require another PR from riak_repl_pb? The version of this on master doesn't include the new n_val and sloppy_quorum records.

**Comment by slfritchie** [comment]
Yup, it does.

**Comment by buddhisthead** [comment]
Uh, I was hoping you would be so kind as to reference any related PRs. I can guess if you want me to :-)

**Comment by slfritchie** [comment]
Heh, it's listed above: https://github.com/basho/riak_repl_pb_api/issues/3

**Comment by buddhisthead** [comment]
Oops. Sorry - didn't see it hiding in the header there. Thanks.

**Comment by buddhisthead** [comment]
Passes riak_test replication2_pg:test_basic_pg_mode_repl13

**Comment by slfritchie** [comment]
Chris said that he'd delay a final merge until the APL usage bug fixed in https://github.com/basho/riak_kv/pull/575 is final.

**Comment by buddhisthead** [comment]
New riak_test in https://github.com/basho/riak_test/pull/304 tests n_val=1 and sloppy_quorum=false, but fails due to https://github.com/basho/riak_kv/issues/575 as mentioned above. When that issue is resolved and test passes, I will mark this PR +1. If @slfritchie is traveling, I'll merge it.

**Comment by buddhisthead** [comment]
+1

**Pull request merged**
