### PR TITLE
Bug/mw/correctly jsonify mutiple fs source sink

### PR DESCRIPTION
**Pull request by lordnull**
2.0 version of #556 .

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Once reviewed, please coordinate documentation update with @metadave and notify product management: cc: @michellep @gburd

**Comment by andrewjstone** [comment]
- [x] make test
- [x] replication2
- [x] dialyzer

**Comment by andrewjstone** [comment]
:+1: 

cc @lordnull @metadave @michellep @gburd

**Comment by bookshelfdave** [comment]
I'd say email docs@basho with any requests so the team is aware of the change. I can help out with writing up docs if necessary.

**Comment by cmeiklejohn** [comment]
@lordnull Can you write up something regarding the change?

**Comment by lordnull** [comment]
Email sent, copied here for posterity:

This is the summary of the change to stats due to https://github.com/basho/riak_repl/pull/562 . This concerns >1.4.8 (including 2.0).

Perviously, client_stats and server_stats for full sync replication stacked all sinks/sources together in one large object:

```
[{pid, pid_one}, {site, <<“site one”>>}, {pid, pid_two}, {site, <<“site two”>>}]
```

Turning this into a json string would have both there, but decoding the string was decoder dependent; if a key exists more than once the decoder may take the first, last, or (in erlang) have multiple copies of the key. For javascript, there’s not multiple copies of the key at all, so the above would become:

```
    {‘pid’:’pid_two’, ‘site’:’site two’}
```

The change takes the site name (which is unique) and splits up the stats based on that, so the final javascript object would look like:

```
    {‘site one’: {‘pid’: ‘pid_one’, ‘site’: ‘site one’}, ‘site two’: {‘pid’: ‘pid_two’, ‘site’: ‘site two’}}
```

This allows one to iterate over the sites (foreach k in object) or lookup a site by a specific name.

**Pull request merged**
