### PR TITLE
Bugfix/mw/keepalive timer from interval to send after 1.4 [JIRA: RIAK-1888]

### PR DESCRIPTION
**Pull request by jonmeredith**
#680 (RIAK-1507) applied to 1.4 series for customer.

### CODE REVIEW

**Comment by jonmeredith** [comment]
+1 3a2863dc08597fa271871282f0598ec90ec864c8

Already created branch for 1.4 to give patch to customer - needs to be applied against 2.0 and 2.1 branches.  @lordnull could you prepare PRs (format-patch/am so we keep sha's if we can) against those two and I'll approve.

**Comment by jonmeredith** [comment]
@bors retry

Unrelated failure

```
module 'riak_core_cluster_mgr'
  module 'riak_core_cluster_mgr_tests'
    *** context setup failed ***
::{badmatch,{error,{already_started,<0.1301.0>}}}
```

**Comment by jonmeredith** [comment]
Quick test - mention of #680 (RIAK-1507) again to see if annotated with JIRA number.

**Comment by jonmeredith** [comment]
Also - does it work the other way - RIAK-1507 (#680)

**Comment by Basho-JIRA** [comment]
Merged in the fix. 

**_[posted via JIRA by Jon Meredith]**_

**Pull request merged**
