### PR TITLE
Enhance/krab/cluster realtime rebalance rebase 2.0

### PR DESCRIPTION
**Pull request by lixen**
Rebase and some squash of #632.

Will start looking at mixed cluster tests as @lordnull proposed.

### CODE REVIEW

**Comment by lixen** [comment]
Now it works with mixed clusters. Tested with a RT only replication2_upgrade.

**Comment by Basho-JIRA** [comment]
This is a fix for - https://github.com/basho/riak/issues/625 

**_[posted via JIRA by Derek Somogyi]**_

**Comment by lordnull** [comment]
:+1: dbc6585

Mixed version test is no more broken than against the 2.0 branch.

**Comment by lordnull** [comment]
Force pushed so yet another pull request doesn't have to come in after a rebase.

**Comment by lordnull** [comment]
:+1: 5573645

Once more with feeling.

**Comment by seancribbs** [comment]
> Once more with feeling.

https://www.youtube.com/watch?v=h2vihYpsE1Y

**Comment by Basho-JIRA** [comment]
According to the PR notes - https://github.com/basho/riak_repl/pull/651

The PR has been reviewed and approved.  Closing this issue. 

**_[posted via JIRA by Derek Somogyi]**_

**Pull request merged**
