### PR TITLE
Address issue 611: acknowledge dropped puts due to bucket type mismatches

### PR DESCRIPTION
**Pull request by bowrocker**
The repl bucket types implementation is failing to acknowledge puts that are dropped on the sink, which leaves the dropped item in the RTQ, which will eventually fill. 
- Make sure to call DoneFun() in the mismatch case, so the drop will be acknowledged and cleared.
- Make logging of the mismatch a debug.
- Make the logging report the offending bucket type.
- Add a counter of mismatch events and fire a timer to report it. 
- Add a configuration parameter to control the interval of reporting: bucket_type_drop_report_interval, default 10s.

Issue: https://github.com/basho/riak_repl/issues/611
Riak test: https://github.com/basho/riak_test/pull/676
### Review checklist
- [x] manual verification of code
- [x] eunit (w/ gist of output)
- [x] EQC (w/ gist of output)
- [x] riak_test (w/ gist of output)
- [x] Dialyzer
- [x] XRef
- [ ] Coverage reports
- [ ] internal docs (design docs)
- [ ] man pages

### CODE REVIEW

**Comment by bowrocker** [comment]
This PR is against 2.0; the original PR was against develop:

https://github.com/basho/riak_repl/pull/612

**Comment by kellymclaughlin** [comment]
- Dialyzer output: https://gist.github.com/4d28c5fbef93ccfa28fd
- Xref output: https://gist.github.com/08c581962df56cc3cfdf

**Comment by kellymclaughlin** [comment]
Verified that the `repl_bucket_types` riak_test with the modifications from https://github.com/basho/riak_test/pull/676 fails using `2.0` and passes using `bugfix/jra/issue-611`

Test output: https://gist.github.com/96f7c11fa8970c70b1ba

**Comment by kellymclaughlin** [comment]
I am seeing one test failure when running `make test` on this branch, but I see the exact same failure  on `develop` and `2.0`. It appears to be an issue with state from other tests affecting the result of the `riak_repl2_rtsource_conn` tests because the test passes every time when run standalone. Also, all of the tests pass on the builders with this change so I am not concerned.

Here is the failure output:

```
riak_repl2_rtsource_conn: riak_repl2_rtsource_conn_test_...*failed*
in function riak_repl2_rtsource_conn:'-connect/1-fun-0-'/2 (src/riak_repl2_rtsource_conn.erl, line 497)
in call from riak_repl2_rtsource_conn:connect/1 (src/riak_repl2_rtsource_conn.erl, line 493)
**error:{assertEqual_failed,[{module,riak_repl2_rtsource_conn},
                     {line,497},
                     {expression,"RTQStats"},
                     {expected,[{percent_bytes_used,0.0},
                                {bytes,0},
                                {max_bytes,104857600},
                                {consumers,[]},
                                {overload_drops,0}]},
                     {value,[{percent_bytes_used,0.0},
                             {bytes,0},
                             {max_bytes,234},
                             {consumers,[]},
                             {overload_drops,0}]}]}


=======================================================
  Failed: 1.  Skipped: 0.  Passed: 187.
```

Here is the complete test run output: https://gist.github.com/6cf39ef64bee36813905

**Comment by kellymclaughlin** [comment]
The test failure I mentioned in the previous comment can manifest in another way as well, but again this happens on `develop` and `2.0` as well as this branch so it should not hold up this change.

```
OK, passed 250 tests

43.32% {riak_repl2_rtq_eqc,push,3}
42.16% {riak_repl2_rtq_eqc,push,2}
8.37% {riak_repl2_rtq_eqc,reregister_consumer,2}
6.16% {riak_repl2_rtq_eqc,test_init,1}
..........................................................................................................................................................................................................................................................
OK, passed 250 tests
riak_repl2_rtsource_conn: riak_repl2_rtsource_conn_test_...*skipped*
undefined
*unexpected termination of test process*
::{badmatch,{error,eaddrinuse}}

=======================================================
  Failed: 0.  Skipped: 0.  Passed: 187.
One or more tests were cancelled.
```

**Comment by bowrocker** [comment]
@borshop merge

**Comment by kellymclaughlin** [comment]
Verified the following replication tests pass with this change:
- `repl_bucket_types`
- `replication2`
- `replication2_upgrade`
- `replication2_rt_sink_connection`
- `replication2_fsschedule`
- `replication2_dirty`
- `replication2_rt_sink_connection`
- `replication2_fsschedule`
- `replication2_dirty`

**Comment by kellymclaughlin** [comment]
This change looks good. Nice job!

:+1:

**Comment by bowrocker** [comment]
Thank you, @kellymclaughlin!

**Pull request merged**
