### PR TITLE
Couple of simple bugs noticed while reading code

### PR DESCRIPTION
**Pull request by bsparrow435**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
:+1:, however, I would like to see the commit messages be a bit more descriptive about the changes involved.

**Comment by cmeiklejohn** [comment]
Please be sure that this makes it into the kill bill so it's accounted for and we don't forget to merge it.

**Comment by bsparrow435** [comment]
Yep, I need to do a better job at that. Added to kill bill and merging.

**Comment by cmeiklejohn** [comment]
Derp, I was hoping we could rebase/squash these commits before we merged.  Also, don't forget to delete the branch so they don't hang around forever.

**Pull request merged**
