### PR TITLE
Remove extraneous noreply from riak_repl2_rtsource_conn:reconnect

### PR DESCRIPTION
**Pull request by ian-mi**
Fixes issue #666 (RIAK-1480) (RIAK-1669) by removing the noreply from the reconnect function. Perhaps type signatures should be added to catch these types of errors.

### CODE REVIEW

**Comment by bsparrow435** [comment]
Have test for this, hoping to merge later today.

**Comment by bsparrow435** [comment]
This test is awaiting a merge. Can't seem to get anyone to review any of my tests...

**Comment by jonmeredith** [comment]
@bsparrow435 sorry man - trying to get a bunch of this triaged.Will try and get there next week.

**Comment by bsparrow435** [comment]
Test showing issue: https://github.com/basho/riak_test/pull/811

Test also checks to make sure sinks are rebalancing after a node restart on the sink cluster. Fails this part of the test about 50% of the time. Main purpose though is to display the badrecord crash.

**Comment by lordnull** [comment]
:+1: 4ab522121d082500c853fd28d5dc827223cc3634

Confirmed using riak_test (when the other thing it was testing passed).

**Comment by JeetKunDoug** [comment]
@borshop merge

**Pull request merged**
