### PR TITLE
Leader reg name change

### PR DESCRIPTION
**Pull request by jonmeredith**
Fix for the gen_leader messages reported in bz://960

### CODE REVIEW

**Comment by dizzyd** [comment]
+1, based on code survey.

**Comment by slfritchie** [comment]
Just a bit of housekeeping: is this pull request going to survive?  Discussion yesterday suggested that this patch would be abandoned?

**Comment by jonmeredith** [comment]
The patch should survive so we can do rolling upgrades.

**Comment by dizzyd** [comment]
+1.

**Pull request merged**
