### PR TITLE
Bloom serialization.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Don't perform serialization of the Bloom filter when not required.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
cc: @Vagabond

**Comment by andrewjstone** [comment]
- [x] code review
- [x] replication2
- [x] eunit
- [ ] dialyzer
- [x] xref

**Comment by Vagabond** [comment]
I've done all of the checklist already, just finishing running repl_aae_fullsync. Dialyzer is failing, but it was failing before.

**Comment by andrewjstone** [comment]
Thanks @Vagabond. This review is all yours :)

**Comment by Vagabond** [comment]
+1

**Comment by cmeiklejohn** [comment]
Thanks.

**Pull request merged**
