### PR TITLE
Enhance/krab/cluster realtime rebalance otp

### PR DESCRIPTION
**Pull request by lixen**
Real-time rebalance as described in
https://gist.github.com/krestenkrab/4b1a493469ff28ba5b9d

### CODE REVIEW

**Comment by jonmeredith** [comment]
aka RIAK-1181 - will smart commits work it out...

**Comment by lordnull** [comment]
Code looks clean. Could use a rebase. when I rebased it on top of 2.0, it did so cleanly. It passes the appropriate r_t; however there doesn't appear to be any mixed version cluster tests for this.

**Comment by runesl** [comment]
Thanks for reviewing. We'll add a mixed source cluster test.

**Comment by lixen** [comment]
Is it possible to change target branch for a PR?

**Pull request closed without merging**
