### PR TITLE
Use iterator_refresh option during vnode folds

### PR DESCRIPTION
**Pull request by andrewjstone**
use riak_kv_vnode:fold/4 instead of /3 in most places

### CODE REVIEW

**Comment by andrewjstone** [comment]
Should be merged with these PRs:
- https://github.com/basho/riak_kv/pull/830
- https://github.com/basho/riak_core/pull/520

**Comment by cmeiklejohn** [comment]
seems good, if the related PRs are good. :+1:

**Comment by Vagabond** [comment]
So, because of deadlocks with handoff, I switched the vnode folds to riak_core_vnode_master:command_return_vnode over in #536 

I'm guessing this PR will need to be reworked.

**Comment by bookshelfdave** [comment]
failing replication2 test against this branch using bitcask: https://gist.github.com/metadave/9142020

I'm going to verify the test without the patch, brb.

**Comment by bookshelfdave** [comment]
@andrewjstone I'd like replication2 to pass before +1'ing this. The latest run in Giddyup shows it failing the same way: http://giddyup.basho.com/#/projects/riak_ee/scorecards/85/85-507-replication2-centos-6-64/40594

**Comment by andrewjstone** [comment]
@metadave replication2 passes for me now after kelly merged in #542 to develop and I rebased ajs-iterator-refresh. We're waiting for the test to run on giddyup still. Only dialyzer failed, which caused the yellow merge indicator on this PR, and it's in the process of being fixed elsewhere.

**Comment by bookshelfdave** [comment]
+1, passes r_t replication w/ bitcask + eleveldb.

**Pull request merged**
