### PR TITLE
Only include atom in connection error stat

### PR DESCRIPTION
**Pull request by ian-mi**
Including the entire error reason tuple in the connection error can
cause each connection error to create a new folsom statistic. To avoid
this, only save the primary atom of the error reason in the statistic.

Addresses issue #711 (RIAK-1623) (RIAK-2231).

### CODE REVIEW

**Comment by bsparrow435** [comment]
+1 from me

**Comment by jvoegele** [comment]
:+1: 12b3e03

**Comment by JeetKunDoug** [comment]
@ian-mi could you please resubmit this PR against the 2.0 branch of repl, and then forward-merge it once it's there into 2.1/develop?

**Comment by JeetKunDoug** [comment]
This is being completed via merge from 2.0->2.1->develop, so I'm going to close this PR.

**Pull request closed without merging**
