### PR TITLE
Handle node down correctly.

### PR DESCRIPTION
**Pull request by lordnull**
Remove the node entry, not the world, from state.

### CODE REVIEW

**Comment by jonmeredith** [comment]
Turns out nodeup was broken too.  Fixed and corrected formatting.

**Comment by bookshelfdave** [comment]
This file has been moved to riak_core: https://github.com/basho/riak_core/blob/master/src/riak_core_tcp_mon.erl, I'm assuming we'll have to merge the change in both places.

**Comment by bookshelfdave** [comment]
Can we get an eunit test for this?

**Comment by buddhisthead** [comment]
This PR has been subsumed by https://github.com/basho/riak_repl/pull/273

**Pull request closed without merging**
