### PR TITLE
AAE fullsync may never terminate

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Using AAE fullsync when a bucket has differing `n_val` between the source and sink clusters can cause the fullsync process to go into an infinite loop. This is due to the manner in which AAE fullsync handles this situation combined with a problem with handling strategy specification in `riak_repl2_fssource`. 

In the case of buckets with conflicting `n_val` values the `riak_repl_aae_source` worker is terminated for the partition and `riak_repl2_fssource` [downgrades](https://github.com/basho/riak_repl/blob/develop/src/riak_repl2_fssource.erl#L178) the strategy to `keylist` and establishes a new connection via the connection manager. 

What should happen next is that the fullsync for the partition is retried using the keylist strategy. In actuality what happens is that AAE fullsync is again selected as the strategy and the AAE tree comparison begins again and then again fails. This process repeats _ad infinitum_. This can be demonstrated by running the `repl_aae_fullsync_custom_n` riak_test. 

The reason this happens is that `riak_repl2_fssource` checks the value of the `fullsync_strategy` environment variable every time [`decide_our_caps`](https://github.com/basho/riak_repl/blob/develop/src/riak_repl2_fssource.erl#L250) is called. In the case of AAE fullsync, where `fullsync_strategy` must be set for it to be enabled this has the effect of overriding the attempt to downgrade to the `keylist` strategy and results in the fullsync never terminating. 

The fix to this problem is to change `riak_repl2_fssource` to only check the `fullsync_strategy` environment variable during initialization and to treat the `strategy` field of the state record as the canonical value for the current requested strategy instead of repeatedly going back to the application environment to obtain this value. This prevents the downgraded strategy value from being overwritten and allow the fullsync to complete even in situations of differing `n_val` values among clusters.

### CODE REVIEW

**Comment by bookshelfdave** [comment]
repl_aae_fullsync [passes](https://gist.githubusercontent.com/metadave/9196647/raw/8011762ebe4a65816c04112522997096b5a06678/foo.out)

+1, although you might want @lordnull @cmeiklejohn or @bowrocker's +1 as well.

**Comment by bookshelfdave** [comment]
repl_aae_fullsync_custom_n  test results [here](https://gist.githubusercontent.com/metadave/9197292/raw/eeb31bfaefc304a9e89594fa40db737abb8c1c21/foo.out)

**Comment by cmeiklejohn** [comment]
Did we ever run replication2 against this, considering the change to fssource?

**Comment by kellymclaughlin** [comment]
> Did we ever run replication2 against this, considering the change to fssource?

Yep, it was run and passed prior to merging.

**Pull request merged**
