### PR TITLE
Ensure we update the bloom for object differences.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Fix a bug where we incremented the count of modified objects, but failed
to update the bloom filter accordingly preventing objects from being
replicated during fullsync.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Backport of #511.

**Comment by kellymclaughlin** [comment]
For the record, [this](https://github.com/basho/riak_kv/pull/818) riak_kv PR is also needed as part of the fix.

**Comment by kellymclaughlin** [comment]
+1 to merge

**Comment by Vagabond** [comment]
+1 from me, too.

**Pull request merged**
