### PR TITLE
Merge riak_repl sweeper code to develop

### PR DESCRIPTION
**Pull request by nickelization**
Just one small change that Mikael made to riak_repl for his sweeper code.

### CODE REVIEW

**Comment by JeetKunDoug** [comment]
+1

**Comment by ian-mi** [comment]
+1

**Comment by fadushin** [comment]
+1

**Comment by JeetKunDoug** [comment]
thumbot merge

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot merge

**Pull request merged**
