### PR TITLE
Don't attempt to send heartbeat when invalid.

### PR DESCRIPTION
**Pull request by andrewjstone**
Don't attempt to send the heartbeat message when it's misconfigured as
a value which is not an integer, which causes the process to crash,
triggering a memory leak and unbounded growth in the binary heap.

A cmeik and andrew stone joint.

cc: @jcapricebasho @kellymclaughlin

### CODE REVIEW

**Comment by andrewjstone** [comment]
Resolves #579.

**Comment by andrewjstone** [comment]
We may want to add a validator in cuttlefish to ensure that this value is an integer or undefined.  cc: @joedevivo

**Comment by kellymclaughlin** [comment]
Nice job. Changes look good, just running through some testing. Is it worth also opening a PR for this change against the `1.4` branch just in case we have to do another 1.4.X release?

**Comment by kellymclaughlin** [comment]
I verified that the binary memory holds steady when using different sized key ranges with the `repl_rt_heartbeat_interval` test. Also verified `replication2` passes with this change.

:+1:

**Comment by cmeiklejohn** [comment]
@borshop merge

**Pull request merged**
