### PR TITLE
Update AAE fullsync to support bucket types V2

### PR DESCRIPTION
**Pull request by ian-mi**
This reverts commit 078f16315c494ea06bd1c1b5f79aece43b09ff74. See pull request #665.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
:+1:

Seems straightforward.

One question: does this assume the bucket type exists on the remote side and has the same configuration?  It seems to, unless I'm missing something obvious...

**Comment by ian-mi** [comment]
No, the put path uses riak_repl_util:do_repl_put which checks that the bucket type exists and matches the remote hash. This was why the code needed to be moved from using bin_put to put, as bin_put assumes that its input is an object while put just passes its input to do_repl_put. I believe Sparrow's test also checks that mismatched types are rejected.

**Comment by bsparrow435** [comment]
It does indeed, thanks for the review @cmeiklejohn

**Comment by cmeiklejohn** [comment]
Is this not a bors-enabled repo?

**Comment by cmeiklejohn** [comment]
:+1: 00040f9

**Comment by jonmeredith** [comment]
bors out all the way... http://bors.bos1:8000/bors.html?repo=riak_repl

On Fri, May 22, 2015 at 11:57 AM, Christopher S. Meiklejohn <
notifications@github.com> wrote:

> Is this not a bors-enabled repo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/basho/riak_repl/pull/682#issuecomment-104729415.

## 

Jon Meredith
Chief Architect
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by cmeiklejohn** [comment]
I realized I forgot to approve the commit in the right way.

**Comment by cmeiklejohn** [comment]
This will merge this change into develop; what other branches do we want to target with this patch?

**Comment by jonmeredith** [comment]
I would argue for 2.0 branch and 2.1 branch as it's a significant bug for
adoption of 2.0 features.

On Fri, May 22, 2015 at 12:15 PM, Christopher S. Meiklejohn <
notifications@github.com> wrote:

> This will merge this change into develop; what other branches do we want
> to target with this patch?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/basho/riak_repl/pull/682#issuecomment-104735375.

## 

Jon Meredith
Chief Architect
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by cmeiklejohn** [comment]
Actually, @ian-mi, before we merge, can you modify the commit message to be a bit more descriptive?

**Comment by jonmeredith** [comment]
Is this PR complete?  A quick scan of the code didn't show me where the BTHash is being generated for send_missing in riak_repl_aae_source (did not check keylisting).

What is the impact of running this on a cluster with mixed versions on both sides?  Unclear to me if the behavior has been defined.

Given original issue #663 (RIAK-1292) (RIAK-1294) (RIAK-1295) (RIAK-1736), it seems like we cannot send objects with bucket types over fullsync as that will crash the receiver and we will make no progress at all.

Options:
1) Increment the protocol version (need to investigate if it's fullsync, or the individual AAE/keylist methods) to determine if the BT object can be sent.  If it can, great. If not, do not send the object so that default objects can be sent.  LOUDLY log a count of the objects not sent and recommend an upgrade to a version that fixes the issue.

2) Continue to let it crash and make that be the forcing function for upgrades.  It's broken already, so this does fix it.

Thoughts @ian-mi @bsparrow435 @cmeiklejohn ?

**Comment by ian-mi** [comment]
Keylist fullsync should already work with bucket types. The BTHash was already being generated in enocde_obj_msg, which keylist fullsync uses. This PR adds support to encode_obj_msg for the w2 wire format which AAE fullsync uses (but keylist does not), and adds support for the BTHash to the receiver by calling decode_obj_msg and using do_repl_put instead of bin_put.

**Comment by lordnull** [comment]
+1 00040f9d61c3d9371ea2f0c95a4778f8e0b3ef41

As expected, this passes the [test meant for it](https://github.com/basho/riak_test/pull/797). There was mention of concerns about speed/efficiency. While there is a speed penalty here, after running the repl_aae_fullysnc_benchmark test multiple times both with and without this patch, I have two posibilities. I either do not have a reliable benchmark setup, or any slow down introduced by this patch is small enough that it is within the speed variance of a normal run (e.g., no detectible change).

For posterity, the results in seconds:

| with? | run 1 | run 2 | run 3 | avg |
| --- | --- | --- | --- | --- |
| Without | 50.75 | 40.70 | 34.68 | 42.04 |
| With | 46.74 | 47.74 | 30.65 | 41.71 |

**Comment by JeetKunDoug** [comment]
@ian-mi at some point you suggested you could update this (or at least investigate) doing the decoding in worker process rather than where it is now - see https://github.com/basho/riak_repl/pull/665#issuecomment-120999465 for context if necessary (as I had to). If possible, we'd like to get that done before we merge this. If you don't have time right now, please let @jonmeredith know and we'll try to find someone else to work on it.

**Comment by cmeiklejohn** [comment]
Are we really considering merging this?  I don't believe the placement of the decoding is the problematic part of this code -- it's the general approach and not considering all of the bucket properties that should be considered for replication.

I've expressed my concern with merging this, as well as the associated bucket type fixes without performing the proper engineering work to support this correctly.

**Comment by ian-mi** [comment]
First draft of rework to decode objects in the fullsync worker instead of AAE sink process has been pushed. Should reduce some overhead. Will finish and test on Monday.

**Comment by ian-mi** [comment]
Confirmed that the new version passes Sparrow's new AAE fullsync / bucket types test as well as the existing fullsync tests. New version should be ready for review / merge.

**Comment by bsparrow435** [comment]
`repl_bucket_types` passes with code, fails without. This test also confirms keylist strategy and mixed versions. :+1:

**Comment by jonmeredith** [comment]
+1 5f28530

Reviewed changes.
Manually recreated bug and confirmed fixed by just upgrading the sink side.
Checked realtime replication and keylist fullsync work with change applied.

Will let bors test the merged code, then decide whether to merge against 2.0 and merge forward or merge into develop and backport.

We still need a permanent solution to the bucket properties used for creating the hash, but will resolve in a different PR.

**Comment by jonmeredith** [comment]
Replaced by #706 (RIAK-1602) (RIAK-1802)

**Pull request closed without merging**
