### PR TITLE
match on # of partitions left in json stats

### PR DESCRIPTION
**Pull request by bookshelfdave**
When repl stats would contain {fullsync, NumberOfPartitions, left}, jsonify_stats would blow up due to invalid pattern matching.
fixes https://github.com/basho/riak_repl/issues/173

Public issue @ https://github.com/basho/riak_ee-issues/issues/1

### CODE REVIEW

**Comment by lordnull** [comment]
No issues on the curl request to get stats when running the code. I'd recommend a unit test though for this bug so we at least take some steps toward getting a corpus of automated testing. Taken from the issue linked to the pr:

Below the webmachine include header:

``` erlang
-ifdef(TEST).
-include_lib("eunit/include/eunit.hrl").
-endif.
```

At the end of the file:

``` erlang
-ifdef(TEST).

jsonify_stats_test_() ->
    [{"fullsync partitions left", fun() ->
      Stats = [{fullsync,63,left},
        {partition,251195593916248939066258330623111144003363405824},
        {partition_start,0.88},{stage_start,0.88}],
      Expected = [{"partitions_left",63},
        {partition,251195593916248939066258330623111144003363405824},
        {partition_start,0.88}, {stage_start,0.88}],
      ?assertEqual(Expected, jsonify_stats(Stats, []))
    end}].

-endif.

```

**Comment by bookshelfdave** [comment]
@lordnull ah, yes. Thank you. I'll add and push.

**Comment by bookshelfdave** [comment]
@lordnull pushed, ty!

**Comment by lordnull** [comment]
Life is good
:+1:

**Pull request merged**
