### PR TITLE
Move connection manager code to core

### PR DESCRIPTION
**Pull request by bookshelfdave**
See https://github.com/basho/riak_core/pull/284

### CODE REVIEW

**Comment by buddhisthead** [comment]
Dave,

I feel like a file is missing: "riak_core_cluster.hrl", but maybe I'm just not seeing it. It should be in deps/riak_repl.

**Comment by bookshelfdave** [comment]
I'll check when I get back home

**Comment by bookshelfdave** [comment]
@buddhisthead .hrl file added. Sorry about that.

**Comment by buddhisthead** [comment]
Please move the appropriate test modules from deps/riak_repl/test from repl to core. Thanks.

**Comment by buddhisthead** [comment]
Tests all pass and changes made.

+1

**Pull request merged**
