### PR TITLE
Jd cuttlefish api

### PR DESCRIPTION
**Pull request by joedevivo**

### CODE REVIEW

**Comment by seancribbs** [comment]
You have some commits in here twice. Any chance you could rebase them out?

**Comment by joedevivo** [comment]
:cry: I tried. In fact, they only got in because @metadave had me rebase a fix he just merged. Can't we just move on?

**Comment by cmeiklejohn** [comment]
squash it into one, and reopen?

**Comment by joedevivo** [comment]
trying, the diff will be the same for review purposes.

**Comment by joedevivo** [comment]
see #484

**Pull request closed without merging**
