### PR TITLE
Pick up develop changes into develop-2.2 [JIRA: RIAK-2961]

### PR DESCRIPTION
**Pull request by lehoff**

### CODE REVIEW

**Comment by JeetKunDoug** [comment]
+1 9517fb1

**Comment by JeetKunDoug** [comment]
Not going to merge into 2.2.0 - maybe 2.2.1?

**Comment by JeetKunDoug** [comment]
create jira issue

**Comment by Basho-JIRA** [comment]
We should test and pick up this fix for 2.2.1 - [~imilligan] was there a corresponding riak_test that caught this somewhere? Specifically talking about https://github.com/basho/riak_repl/pull/759/commits/97af080e694bfb7f9190ec32830767bb04c7e48d. 

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment]
There's no riak_test for this, I think it just breaks the repl status output w/ a bad_match error when the repl leader is undefined. 

**_[posted via JIRA by Ian Milligan]**_

**Comment by Basho-JIRA** [comment]
Need to write a test to prove that this has been fixed.   

***[posted via JIRA by Patricia Brewer]***

**Comment by Basho-JIRA** [comment]
Looking at the code, we can forgo tests for this. Just cherry-pick the change above to 2.0.8/2.2.1 

***[posted via JIRA by Douglas Rohrer]***

**Comment by Basho-JIRA** [comment]
My apologies.  Grabbed the wrong story and updated it.  Put this back to state it was in.   

***[posted via JIRA by Patricia Brewer]***

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak_repl/pull/766 

***[posted via JIRA by Brian Sparrow]***

**Pull request closed without merging**
