### PR TITLE
Prevent potential race condition.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Prevent a potential race condition where services may or may not be
registered by the service manager because of the ordering of
registration, and the nature of cast'ing the registration messages.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@metadave

**Comment by cmeiklejohn** [comment]
Bah, hold on, I screwed up this commit.

**Comment by cmeiklejohn** [comment]
Fixed the commit.

**Comment by bookshelfdave** [comment]
https://github.com/basho/riak_core/pull/470

**Comment by bookshelfdave** [comment]
+1, will need a full run through riak-test

**Pull request merged**
