### PR TITLE
Fix replication2_ssl test for Riak 2.0.5 [JIRA: RIAK-1523]

### PR DESCRIPTION
**Pull request by tburghart**
Fixes replication2_ssl test for Riak 2.0.5

### CODE REVIEW

**Comment by andrewjstone** [comment]
Reviewing....

Code looks good, running test without and with patch.

**Comment by andrewjstone** [comment]
+1  f74768c

replication2_ssl fails without patch, passes with

Nice job @tburghart @lordnull

**Comment by cmeiklejohn** [comment]
+1 f74768c

**Comment by cmeiklejohn** [comment]
@borshop merge

**Comment by Basho-JIRA** [comment]
Comment for JiraBot. 

**_[posted via JIRA by Derek Somogyi]**_

**Pull request merged**
