### PR TITLE
Allow buckets to be fullsynced, but not participate in realtime repl

### PR DESCRIPTION
**Pull request by Vagabond**
This is done via new values for the 'repl' bucket property:
- {repl, both} - both types of replication, same as {repl, true}
- {repl, fullsync} - only fullsync this bucket, no realtime
- {repl, realtime} - only realtime repl this bucket, no fullsync
  
  As noted above, {repl, true} is a synonym for {repl, both} and so old
  configurations will upgrade gracefully.

### CODE REVIEW

**Comment by rzezeski** [comment]
I feel like this could be confusing.  The repl property can now take on two different semantics depending on it's value.  Either it refers realtime+fullsync if true or it refers to just realtime if false.

`repl=true + repl_fullsync=true` - second property is redundant
`repl=false + repl_fullsync=true` - don't do realtime but do fullsync, sorta confusing to see repl=false but in reality it is still occurring
`repl=true + repl_fullsync=false` - fullsync is ignored in this case
`repl=false + repl_fullsync=false` - don't run repl at all

**Comment by Vagabond** [comment]
I agree, do you have a better solution that is less confusing AND backwards compatible?

**Comment by Vagabond** [comment]
Perhaps {repl, fullsync_only} ? But that would be a more complicated patch.

**Comment by rzezeski** [comment]
I'm not sure I would keep backwards compatibility if it leads to confusion.  I wonder if anyone would ever have a reason to do realtime but not fullsync?  Perhaps a caching service that does best attempt to replicate?  I wonder if rather than a binary value it should be a set of repl types, e.g. `{repl, [fullsync, realtime]}`.  Perhaps two booleans, `repl_fullsync` and `repl_realtime` and setting `repl` to true causes both to be true?

**Comment by Vagabond** [comment]
I could live with {repl, (true|realtime|fullsync|)}, and maybe add 'both' as a synonym of 'true'.

**Comment by rzezeski** [comment]
I think that is less confusing and I can't think of a reason not to do it that way.

**Comment by Vagabond** [comment]
Alright, will reformulate patch.

**Comment by Vagabond** [comment]
Re-pushed and updated the issue description to match the new behaviour.

**Comment by jonmeredith** [comment]
works nicely.

+1 merge

test helper code...

```

-module(replh).
-compile([export_all]).

test_buckets() ->
    [{<<"replfalse">>, false},
     {<<"repltrue">>, true},
     {<<"replreal">>, realtime},
     {<<"replfull">>, fullsync},
     {<<"replboth">>, both}].


set_brops() ->
    [riak_core_bucket:set_bucket(B,[{repl, Mode}]) || {B,Mode} <- test_buckets()].


write() ->
    {ok, C} = riak:local_client(),
    [C:put(riak_object:new(B, <<"key">>, atom_to_binary(Mode, utf8))) || {B, Mode} <- test_buckets()].

read() ->
    {ok, C} = riak:local_client(),
    [case C:get(B, <<"key">>) of
         {error, Reason} ->
             {Mode, Reason};
         {ok, RObj} ->
             {Mode, riak_object:get_value(RObj)}
     end || {B, Mode} <- test_buckets()].

clear() ->
    {ok, C} = riak:local_client(),
    [C:delete(B, <<"key">>) || {B, _Mode} <- test_buckets()].
```

**Pull request merged**
