### PR TITLE
Added test and fix to coord_serv not giving list for status.

### PR DESCRIPTION
**Pull request by lordnull**
Fix for #615. For those reviewing, this fix may not actually be enough.

While looking through the code, I noticed that the leader node isn't actually used, it's just checked for. After that, the stats gathered are just for the local node. So, is the current behavior correct at all?

### CODE REVIEW

**Comment by engelsanchez** [comment]
Yes, you are right. It is not used. That seems to have been left behind from the original commit: https://github.com/basho/riak_repl/commit/989d79a30c1fb9e60b0c1136cc976cbaf616f988

I vote for dropping the check entirely. Thanks for looking at this!

**Comment by lordnull** [comment]
The second part to the question is do we want to alter the behavior so it asks all the nodes for stats, or keep it node-local?

**Comment by lordnull** [comment]
For posterity: final decision was to defer determining if local only data was valid to later. Fix the error here first (leader existence causing crash). Open a new issue to determine if we should be trying to gather all node's stats.

**Comment by engelsanchez** [comment]
:+1: 39fa59f

I hit rebuild on buildbot as the eunit tests run was incomplete. I'm not sure why.

**Comment by engelsanchez** [comment]
@borshop merge

**Pull request merged**
