### PR TITLE
Race between riak_repl_pb_get and riak_repl_ring_handler

### PR DESCRIPTION
**Pull request by Vagabond**
As of 1.4, riak_repl_pb_get checks the ring as part of init():

https://github.com/basho/riak_repl/blob/master/src/riak_repl_pb_get.erl#L41

Problem is, that init is done before the riak_repl_ring handler is installed:

https://github.com/basho/riak_repl/blob/master/src/riak_repl_app.erl#L58

https://github.com/basho/riak_repl/blob/master/src/riak_repl_app.erl#L82

So, on a clean node, bad things like this happpen:

```
2013-06-04 18:42:52.206 [error] <0.639.0> gen_server <0.639.0> terminated with reason: bad record di
ct in dict:get_slot/2 line 395
2013-06-04 18:42:52.207 [error] <0.639.0> CRASH REPORT Process <0.639.0> with 0 neighbours exited wi
th reason: bad record dict in dict:get_slot/2 line 395 in gen_server:terminate/6 line 747
2013-06-04 18:42:52.207 [error] <0.324.0> Supervisor riak_api_pb_sup had child undefined started wit
h {riak_api_pb_server,start_link,undefined} at <0.639.0> exit with reason bad record dict in dict:ge
t_slot/2 line 395 in context child_terminated
```

This happens because riak_repl_ring:get_repl_config, if there's no repl config in the ring, returns undefined:

https://github.com/basho/riak_repl/blob/master/src/riak_repl_ring.erl#L67

And everywhere we call get_repl_config, we assume that a valid dict is returned.

For most usages this turns out fine (by accident, I guess), but the change to riak_repl_pb_get introduces a race which can make node startup fail on new nodes.

### CODE REVIEW

**Comment by Vagabond** [comment]
Alternatively, or additionally, we could fix get_repl_config to return initial_config() in the undefined case.

cc @metadave

**Comment by bookshelfdave** [comment]
@Vagabond added initial_config() to get_repl_config

**Comment by bookshelfdave** [comment]
+1 to your changes

**Comment by buddhisthead** [comment]
+1 to your initial_config() change, @metadave.  Please check my recent cleanup. Thank you.

**Comment by bookshelfdave** [comment]
looks good, thanks.

**Pull request merged**
