### PR TITLE
Remove old lines from dialyzer.ignore-warnings [JIRA: RIAK-3242]

### PR DESCRIPTION
**Pull request by nickelization**
These warnings no longer exist. Might as well remove them from this file!

### CODE REVIEW

**Comment by nickelization** [comment]
There is an issue with the unit tests, but it seems to be unrelated to the changes in this PR.

**Comment by raghavkarol** [comment]
Nice work!  

A side note, unrelated to the PR: Looking into the remaining warnings in the `.dialyzer.ignore-warnings` file it's interteresting and concerning that the code works correctly despite the remaining warnings (type contract violations).

**Comment by raghavkarol** [comment]
+1

**Comment by raghavkarol** [comment]
Added a make target to report redundant dialyzer warnings https://github.com/basho/tools.mk/pull/16/files

**Comment by bashopatricia** [comment]
create jira issue

**Comment by Basho-JIRA** [comment]
This was already reviewed and merged to develop on Jan 27: marking as closed. 

***[posted via JIRA by Nick Marino]***

**Pull request merged**
