### PR TITLE
Separate configs and defaults between fs/rt for Riak CS block tombstone filter [JIRA: RIAK-2215]

### PR DESCRIPTION
**Pull request by shino**
This PR is a fix for https://github.com/basho/riak_repl/pull/678.
- Separate config keys into realtime and fullsync for block tombstone fileter and
- Set different default values for them, propagete in realtime and filter away
  in fullsync.

_NOTE_ If possible, it's nice to include this PR in coming Riak Enterprise 2.1.2
release, in which #678 will be included.

---

Copy-and-paste from code comments for why the change is necessary:

```
{true, fullsync} ->
    %% Default for tombstoned blocks is *NO PROPAGATE*.
    %% Tombstoned blocks at fullsync are probably lingering ones.
    %% Propagating them to sink will trigger putting tombstones and
    %% reaping them almost in vein. Coming fullsyncs will again propagate
    %% them again and again.
    app_helper:get_env(riak_repl, ?CONFIG_REPL_BLOCK_TOMBSTONE_FS, false);
{true, realtime} ->
    %% Default for tombstoned blocks is GO AHEAD.
    %% Tombstons put at sink side carry information about overwrite
    %% by its vclock, it enables that sink avoid read phase of
    %% read-before-delete and eases disk load caused by read.
    app_helper:get_env(riak_repl, ?CONFIG_REPL_BLOCK_TOMBSTONE_RT, true)
```

### CODE REVIEW

**Comment by kuenishi** [comment]
@borshop merge

**Comment by Basho-JIRA** [comment]
Put into 2.1.2 and test to see if it breaks anything.  Agreement with Doug, Heather and Seema in content 2.1.2 review.  

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment]
Has already been merged, needs test with real. 

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment]
Merged into 2.1 branch for riak_repl - will be tested in Giddyup in the next run. 

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment]
Patti, Doug,

Thanks for paying attention to this! 

**_[posted via JIRA by Shunichi Shinohara]**_

**Pull request merged**
