### PR TITLE
Backport pipelined AAE fullsync to 1.4

### PR DESCRIPTION
**Pull request by engelsanchez**
This PR backports the pipelined AAE changes from basho/riak_repl#616,
as well as hand picked changes from the 2.0 branch that fixed obvious 
problems or improved tests.  Locally, all eunit tests passed for me on this
branch.

/cc @jonmeredith

### CODE REVIEW

**Comment by jonmeredith** [comment]
Missing a very minor appenv variable rename, should be `fullsync_direct_limit`.

```
diff --git a/src/riak_repl_aae_source.erl b/src/riak_repl_aae_source.erl
index cae1fa7..b2c280f 100644
--- a/src/riak_repl_aae_source.erl
+++ b/src/riak_repl_aae_source.erl
@@ -220,7 +220,7 @@ prepare_exchange(start_exchange, State=#state{index=Partition}) ->
 update_trees(init, State) ->
     NumKeys = 10000000,
     {ok, Bloom} = ebloom:new(NumKeys, 0.01, random:uniform(1000)),
-    Limit = app_helper:get_env(riak_repl, fullsync_direct_limit, ?GET_OBJECT_LIMIT),
+    Limit = app_helper:get_env(riak_repl, fullsync_direct, ?GET_OBJECT_LIMIT),
     Mode = app_helper:get_env(riak_repl, fullsync_direct_mode, inline),
     Buffer = case Mode of
                  inline ->
```

**Comment by engelsanchez** [comment]
@jonmeredith latest on 2.0 seems to have fullsync_direct_limit. It's listed as a change in the history of Joe's branch.  Are you up to date locally? https://github.com/basho/riak_repl/blob/2.0/src/riak_repl_aae_source.erl#L223

**Comment by jonmeredith** [comment]
Hmmm, must have been a bad diff on my part… Rechecking.

**Comment by jonmeredith** [comment]
Code review also complete by Joe, lots of local r_t by Engel, JoeB and JonM.
Merging.

**Pull request merged**
