### PR TITLE
Merge 2.1 into 2.2/0

### PR DESCRIPTION
**Pull request by jonmeredith**

### CODE REVIEW

**Comment by bsparrow435** [comment]
@borshop merge

**Comment by bsparrow435** [comment]
+1 eda887f271e6b05f5c252fac7e80c09a83cc21ae

**Comment by bsparrow435** [comment]
:+1: eda887f271e6b05f5c252fac7e80c09a83cc21ae

**Comment by JeetKunDoug** [comment]
@borshop merge

**Pull request merged**
