### PR TITLE
Missed unregister_q deliver function.

### PR DESCRIPTION
**Pull request by jonmeredith**
Must have forgotten when manually reapplied from early testing to
now.  Should have listened to bors and eqc. Lesson on hubris and shame.

### CODE REVIEW

**Comment by jonmeredith** [comment]
@bsparrow435 would you mind reviewing this too - I missed a clause last time, and EQC was justifiably finding a bug.

**Comment by jonmeredith** [comment]
Stupid unrelated error in `riak_core_cluster_conn_eqc`

```
[{set,{var,1},{call,riak_core_cluster_conn_eqc,send_timeout,[{var,fsm_pid}]}},
 {set,{var,2},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,3},{call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,4},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,5},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,6},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,7},
      {call,riak_core_cluster_conn_eqc,connected_to_remote,[{var,fsm_pid}]}},
 {set,{var,8},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,9},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,10},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,11},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,12},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,13},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,14},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,15},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,16},{call,riak_core_cluster_conn_eqc,cluster_name,[{var,fsm_pid}]}},
 {set,{var,17},
      {call,riak_core_cluster_conn_eqc,cluster_members,[{var,fsm_pid}]}},
 {set,{var,18},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,19},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,20},{call,riak_core_cluster_conn_eqc,cluster_name,[{var,fsm_pid}]}},
 {set,{var,21},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,22},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,23},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,24},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,25},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,26},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,27},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,28},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,29},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,30},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,31},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,32},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,33},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,34},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,35},
      {call,riak_core_cluster_conn_eqc,cluster_members,[{var,fsm_pid}]}},
 {set,{var,36},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,37},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,38},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,39},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,40},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,41},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,42},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,43},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,44},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,45},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,46},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,47},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,48},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,49},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,50},{call,riak_core_cluster_conn_eqc,cluster_name,[{var,fsm_pid}]}},
 {set,{var,51},
      {call,riak_core_cluster_conn_eqc,cluster_members,[{var,fsm_pid}]}},
 {set,{var,52},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,53},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,54},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,55},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,56},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,57},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,58},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,59},{call,riak_core_cluster_conn_eqc,cluster_name,[{var,fsm_pid}]}},
 {set,{var,60},
      {call,riak_core_cluster_conn_eqc,cluster_members,[{var,fsm_pid}]}},
 {set,{var,61},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,62},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,63},{call,riak_core_cluster_conn,stop,[{var,fsm_pid}]}}]
test/riak_core_cluster_conn_eqc.erl:104:<0.2253.0>: 
Cmds: [{initiating_connection,{riak_core_cluster_conn_eqc,send_timeout,1}},
       {connecting,{riak_core_cluster_conn,status,1}},
       {connecting,{riak_core_cluster_conn_eqc,garbage_event,1}}]

test/riak_core_cluster_conn_eqc.erl:107:<0.2253.0>: 
Result: {postcondition,
            {'EXIT',
                {timeout,
                    {gen_fsm,sync_send_all_state_event,
                        [<0.3290.0>,current_state]}}}}

test/riak_core_cluster_conn_eqc.erl:108:<0.2253.0>: 
History: [{eqc_statem_history,
              {initiating_connection,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn_eqc,send_timeout,[<0.3290.0>]},
              [],
              {normal,ok}},
          {eqc_statem_history,
              {connecting,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn,status,[<0.3290.0>]},
              [],
              {normal,{connecting,"FARFARAWAY"}}},
          {eqc_statem_history,
              {connecting,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn_eqc,garbage_event,[<0.3290.0>]},
              [],
              {normal,ok}}]

ok /= {postcondition,
          {'EXIT',
              {timeout,
                  {gen_fsm,sync_send_all_state_event,
                      [<0.3290.0>,current_state]}}}}
Shrinking xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(x10)xx(x1)xxxxxxxxx(0 times)
[{set,{var,1},{call,riak_core_cluster_conn_eqc,send_timeout,[{var,fsm_pid}]}},
 {set,{var,2},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,3},{call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,4},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,5},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,6},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,7},
      {call,riak_core_cluster_conn_eqc,connected_to_remote,[{var,fsm_pid}]}},
 {set,{var,8},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,9},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,10},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,11},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,12},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,13},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,14},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,15},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,16},{call,riak_core_cluster_conn_eqc,cluster_name,[{var,fsm_pid}]}},
 {set,{var,17},
      {call,riak_core_cluster_conn_eqc,cluster_members,[{var,fsm_pid}]}},
 {set,{var,18},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,19},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,20},{call,riak_core_cluster_conn_eqc,cluster_name,[{var,fsm_pid}]}},
 {set,{var,21},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,22},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,23},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,24},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,25},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,26},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,27},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,28},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,29},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,30},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,31},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,32},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,33},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,34},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,35},
      {call,riak_core_cluster_conn_eqc,cluster_members,[{var,fsm_pid}]}},
 {set,{var,36},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,37},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,38},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,39},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,40},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,41},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,42},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,43},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,44},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,45},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,46},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,47},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,48},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,49},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,50},{call,riak_core_cluster_conn_eqc,cluster_name,[{var,fsm_pid}]}},
 {set,{var,51},
      {call,riak_core_cluster_conn_eqc,cluster_members,[{var,fsm_pid}]}},
 {set,{var,52},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,53},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,54},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,55},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,56},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,57},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,58},{call,riak_core_cluster_conn_eqc,poll_cluster,[{var,fsm_pid}]}},
 {set,{var,59},{call,riak_core_cluster_conn_eqc,cluster_name,[{var,fsm_pid}]}},
 {set,{var,60},
      {call,riak_core_cluster_conn_eqc,cluster_members,[{var,fsm_pid}]}},
 {set,{var,61},
      {call,riak_core_cluster_conn_eqc,garbage_event,[{var,fsm_pid}]}},
 {set,{var,62},{call,riak_core_cluster_conn,status,[{var,fsm_pid}]}},
 {set,{var,63},{call,riak_core_cluster_conn,stop,[{var,fsm_pid}]}}]
test/riak_core_cluster_conn_eqc.erl:104:<0.2253.0>: 
Cmds: [{initiating_connection,{riak_core_cluster_conn_eqc,send_timeout,1}},
       {connecting,{riak_core_cluster_conn,status,1}},
       {connecting,{riak_core_cluster_conn_eqc,garbage_event,1}}]

test/riak_core_cluster_conn_eqc.erl:107:<0.2253.0>: 
Result: {postcondition,
            {'EXIT',
                {timeout,
                    {gen_fsm,sync_send_all_state_event,
                        [<0.3290.0>,current_state]}}}}

test/riak_core_cluster_conn_eqc.erl:108:<0.2253.0>: 
History: [{eqc_statem_history,
              {initiating_connection,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn_eqc,send_timeout,[<0.3290.0>]},
              [],
              {normal,ok}},
          {eqc_statem_history,
              {connecting,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn,status,[<0.3290.0>]},
              [],
              {normal,{connecting,"FARFARAWAY"}}},
          {eqc_statem_history,
              {connecting,{ccst_state,undefined,undefined}},
              {call,riak_core_cluster_conn_eqc,garbage_event,[<0.3290.0>]},
              [],
              {normal,ok}}]

ok /= {postcondition,
          {'EXIT',
              {timeout,
                  {gen_fsm,sync_send_all_state_event,
                      [<0.3290.0>,current_state]}}}}
riak_core_cluster_conn_eqc:74: eqc_test_...*failed*
in function riak_core_cluster_conn_eqc:'-eqc_test_/0-fun-3-'/1 (test/riak_core_cluster_conn_eqc.erl, line 74)
**error:{assertEqual_failed,[{module,riak_core_cluster_conn_eqc},
                     {line,74},
                     {expression,"eqc : quickcheck ( eqc : testing_time ( 30 , ? QC_OUT ( prop_cluster_conn_state_transition ( ) ) ) )"},
                     {expected,true},
                     {value,false}]}
  output:<<"Starting Quviq QuickCheck version 1.36.1
   (compiled at {{2015,9,11},{11,37,51}})
Licence for Basho (Continuous Integration) reserved until {{2016,3,1},
                                                           {20,50,13}}
">>
```

**Comment by bsparrow435** [comment]
:+1: 966f1ec94f134244f7441af9ea628200a056d3e5

**Comment by jonmeredith** [comment]
@borshop merge

**Pull request merged**
