### PR TITLE
Move tcp-mon, connection and service manager supervisors from replication to core

### PR DESCRIPTION
**Pull request by buddhisthead**
In order for the connection and service manager to be fully moved to core, we need to move
their supervisors. Also, I've moved the tcp_mon supervisor because it's really a core thing too.

The matching PR fro core is here...
https://github.com/basho/riak_core/pull/383

Doesn't that code look cleaner now!

NOTE: Please do not merge after the +1 here. I need to press the merge buttons on both riak_repl and riak_core at nearly the same time :-) Thanks.

### CODE REVIEW

**Comment by bookshelfdave** [comment]
This PR needs to be rebased to pull in the cuttlefish changes. It fails to build otherwise: https://gist.github.com/metadave/14b0a4672ee68e1e872f

**Comment by buddhisthead** [comment]
The poor thing is so old. I will rebase. Thanks!

**Comment by buddhisthead** [comment]
I had to force push after the rebase. Please get a fresh version of this branch. I did confirm correct build after cloning a fresh ee and checking out vet-conn-mgr-supervisors in _both_ riak_repl and riak_core.

**Comment by cmeiklejohn** [comment]
I think last time we discussed this, we had decided to move all of this back to repl until we were able to clean up some of the more problematic areas and get the design right, isn't that correct @jonmeredith?

**Comment by buddhisthead** [comment]
Yes, we are punting on this PR for 2.0.

**Comment by cmeiklejohn** [comment]
Closing.

**Pull request closed without merging**
