### PR TITLE
Fixes ack issues and queue fill up w/ bi-directional cascading

### PR DESCRIPTION
**Pull request by lordnull**

### CODE REVIEW

**Comment by bsparrow435** [comment]
Passes my manual tests reproducing the issue. :+1:

**Comment by bookshelfdave** [comment]
this needs to get into `develop` as well

**Comment by bowrocker** [comment]
### Testing
- [x] manual verification of code
- [ ] eunit     (w/ gist of output) 
- [ ] EQC       (w/ gist of output) 
- [x] riak_test output: https://gist.github.com/bowrocker/cb630ec2f7788d6993cf
- [ ] Dialyzer
- [ ] XRef
- [ ] Coverage reports

riak test appears to work.

:+1:

**Comment by bookshelfdave** [comment]
can you run the replication2 as well?

might want to note that EQC currently fails

(I'm just worried about sending out beams for this one)

**Comment by bookshelfdave** [comment]
I forgot that replication2 is somewhat broken atm.
This branch should fix the problem: https://github.com/basho/riak_test/tree/dp_replication2_fix

**Comment by bowrocker** [comment]
Replication2 now works with 1.4.3 tag: https://gist.github.com/bowrocker/4501ae2ff8ff35bba8a9

**Pull request merged**
