### PR TITLE
Improve realtime migration when riak_repl is stopping

### PR DESCRIPTION
**Pull request by Vagabond**
These changes are intended to avoid dropping realtime messages that
happen or are pending during riak_repl stopping. The key changes are
that we try to send realtime messages to the rtq_proxy first, which
avoids a race with the process dictionary. We also explicitly stop() the
repl2_rtq so that we can gurantee terminate() completes. To do that, we
needed to make it a transient child of its supervisor, so it wouldn't
immediately restart.

### CODE REVIEW

**Comment by Vagabond** [comment]
See also:

basho/riak_kv#454
basho/webmachine#106
basho/riak_test#128

**Comment by bookshelfdave** [comment]
looks good, riak_test passes. A +1 depends on any pending changes to webmachine.

**Comment by bookshelfdave** [comment]
replication2 test passes with latest webmachine tweaks.
+1

**Comment by seancribbs** [comment]
@metadave @Vagabond What are this and basho/riak_test#128 waiting on?

**Pull request merged**
