### PR TITLE
Merge 2.0 into develop 2.2

### PR DESCRIPTION
**Pull request by fadushin**

### CODE REVIEW

**Comment by jvoegele** [comment]
+1 e2789099b06de8176fab8d5c9b7916a11183c620

**Comment by fadushin** [comment]
@borshop merge

**Comment by nickelization** [comment]
✈️  #747 (RIAK-1870) (RIAK-2149) ✈️

**Comment by hazen** [comment]
I spent some quality time with this PR on Tuesday crossing the Atlantic...

**Pull request merged**
