### PR TITLE
bring additional 1.4 changes to develop for 2.0

### PR DESCRIPTION
**Pull request by bookshelfdave**

### CODE REVIEW

**Comment by bookshelfdave** [comment]
@cmeiklejohn @lordnull @bowrocker

**Comment by cmeiklejohn** [comment]
:+1: on most of this, but there are some changes regarding masks, and anya compat that I don't know enough about.

**Comment by cmeiklejohn** [comment]
The branch doesn't compile because of the `get_ring()` call which is no longer required.

**Comment by cmeiklejohn** [comment]
:+1: to merge; do it.

**Pull request merged**
