### PR TITLE
Fix bug when passing utc timestamps into httpd_util:rfc1123/1.

### PR DESCRIPTION
**Pull request by martincox**
This function expects a localtime and throws an exception otherwise. This is evident when the clocks go forward for DST and a time falling in the skipped hour is passed into the function.

The fact that an exception is thrown is down to a bug in OTP which was patched in 20.1.

### CODE REVIEW

**Comment by martincox** [comment]
@russelldb @Vagabond @binarytemple-external needs a quick review / merge if anyone can spare a couple of mins?

**Comment by ghost** [comment]
I don't have review rights, but I'll give it a +1 

```
5> httpd_util:rfc1123_date(calendar:universal_time_to_local_time(DateTime)).
"Mon, 01 Jan 2018 00:00:00 GMT"
6> f(DateTime).                
ok
7> DateTime = {{2013, 9, 19}, {20, 51, 7}}.                                 
{{2013,9,19},{20,51,7}}
8> httpd_util:rfc1123_date(calendar:universal_time_to_local_time(DateTime)).
"Thu, 19 Sep 2013 20:51:07 GMT"
```

I guess from your commit message we can dump it later when everything is running on 20.2+ but that's the future, better to think in the present.

**Comment by ghost** [comment]
fixes #775

**Review by russelldb — APPROVED** [review]
LGTM +1

**Pull request merged**
