### PR TITLE
Use valid API for starting strategy modules in riak_repl_tcp_server

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Commit 0b6acd2d introduced a change to the API for starting fullsync strategy modules (The commit was part of PR #520). Specifically, a parameter was added to the `start_link` function for each fullsync strategy module. Change the call in `riak_repl_tcp_server` to start the strategy module to include the additional required parameter. The extra parameter indicates the replication protocol level supported and is set to `{1,0}` in this case since the code is only executed for legacy connections.

This change should resolve the failure of many of the `replication2_pg` tests. The following in particular:
- replication2_pg:test_mixed_pg
- replication2_pg:test_mixed_pg_ssl
- replication2_pg:test_12_pg_mode_repl12_ssl 
- replication2_pg:test_12_pg_mode_repl12 
- replication2_pg:test_12_pg_mode_repl_mixed 
- replication2_pg:test_12_pg_mode_repl_mixed_ssl

In addition to verifying these tests, please also double check the use of `{1,0}` in this change. I believe it is correct, but I would like someone with more history with replication to verify that.

### CODE REVIEW

**Comment by bowrocker** [comment]
- [x] code review
- [x] riak_tests: https://gist.github.com/bowrocker/8d5719a396705b9d3e9d
- [x] eunit
- [ ] dialyzer
- [x] xref

**Comment by lordnull** [comment]
Confirm that tests pass, and looks like the choice of {1,0} for the proto version is appropriate.

**Comment by bowrocker** [comment]
:+1:

**Comment by kellymclaughlin** [comment]
:+1:  e66d8f7

**Comment by cmeiklejohn** [comment]
Why didn't this one auto merge?

**Comment by kellymclaughlin** [comment]
:+1: e66d8f7

**Comment by Vagabond** [comment]
:+1:  64723e0

**Comment by Vagabond** [comment]
Remember kids, if the tip of the branch changes, it invalidates any prior +1s. It was having trouble before because we'd hit the API request limit. That is now fixed.

**Comment by Vagabond** [comment]
Also, you'll need to tell borshop to merge it, since we turned off automerge.

**Comment by kellymclaughlin** [comment]
@borshop merge

**Comment by cmeiklejohn** [comment]
Should @borshop delete the branch post-merge?

**Comment by Vagabond** [comment]
We can make it, if desired.

**Comment by cmeiklejohn** [comment]
So, is the expectation that the author of the change deletes it?

**Comment by Vagabond** [comment]
Or we patch bors to do it, if we decide we always want to delete branches (you can still recover them)

**Comment by kellymclaughlin** [comment]
+1 to bors doing it

**Comment by cmeiklejohn** [comment]
Agreed; +1 as well.

**Pull request merged**
