### PR TITLE
Prevent sink cluster fullsync stalls with tcp errors.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
In the event that the tcp connection errors without completing
full-sync, and when the max fssinks is not configured and defaulted to
one, this causes the aae_sink process to terminate normally, but not
propagate errors to the fssink process.  This causes an abandoned fssink
process, which locks out any future reservations for fullsync causing
replication to stall indefinitely on the sink cluster.

In the event that max fssink setting is not configured to one, and
specified at another value, tcp errors can cause available reservation
slots to be depleted over time.

This problem was discovered with repl_aae_fullsync in riak_test and
should be forward ported to the 2.0 release in addition to the test.

This could also be part of the issue observed by OpenX, in addition to the
not_built handling.

cc: @bsparrow435 @jcapricebasho

### CODE REVIEW

**Comment by Vagabond** [comment]
This looks like a good change, although I question why the AAE implementation of fullsync defeats the abstraction layer in fssink that was intended to insulate fullsync implementations from dealing with sockets at all.

I'm +1 on a reading of the code, although I have not run the tests.

**Comment by cmeiklejohn** [comment]
Oops, I said OpenX, but I meant Riot Games.

**Comment by jcapricebasho** [comment]
2013-12-18 10:51:13.413 [notice] <0.4182.0>@riak_repl_console:fullsync:436 [user] Start Fullsync Replication to cluster "SINK"
2013-12-18 10:51:13.473 [info] <0.4186.0>@riak_repl2_fssource:connect:279 connecting to remote {{127,0,0,1},10046}
2013-12-18 10:51:13.473 [info] <0.4186.0>@riak_repl2_fssource:connect:295 connection ref #Ref<0.0.0.17085>
2013-12-18 10:51:13.474 [info] <0.4187.0>@riak_core_connection:try_ssl:208 "SOURCE" and "SINK" agreed to not use SSL
2013-12-18 10:51:13.475 [info] <0.4186.0>@riak_repl2_fssource:handle_call:70 fullsync connection to {{127,0,0,1},10046} for 548063113999088594326381812268606132370974703616
2013-12-18 10:51:13.475 [info] <0.4186.0>@riak_repl2_fssource:handle_call:82 Got caps: [{strategy,aae}]
2013-12-18 10:51:13.475 [info] <0.4186.0>@riak_repl2_fssource:handle_call:84 Common strategy: aae
2013-12-18 10:51:13.489 [info] <0.4188.0>@riak_repl_aae_source:init:76 AAE fullsync source worker started for partition 548063113999088594326381812268606132370974703616
2013-12-18 10:51:13.489 [info] <0.4188.0>@riak_repl_aae_source:terminate:136 Terminating.
2013-12-18 10:51:13.489 [error] <0.4188.0> gen_fsm <0.4188.0> in state prepare_exchange terminated with reason: bad return value: closed
2013-12-18 10:51:13.490 [info] <0.4186.0>@riak_repl2_fssource:handle_info:209 ignored handle_info {'DOWN',#Ref<0.0.0.17101>,process,<0.4188.0>,{bad_return_value,closed}}
2013-12-18 10:51:13.490 [error] <0.4188.0> CRASH REPORT Process <0.4188.0> with 0 neighbours exited with reason: bad return value: closed in gen_fsm:terminate/7 line 611

**Comment by cmeiklejohn** [comment]
How do we feel about merging this into 1.4?

**Comment by cmeiklejohn** [comment]
Closing, incorporated into #500.

**Pull request closed without merging**
