### PR TITLE
Update bucket properties hash for write_once.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Update the bucket properties hash to take the write_once bucket property
into consideration; additionally, remove the allow_mult and
last_write_wins restrictions.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
If this looks good; will open PRs for 2.0.6 and 2.1.2.

**Comment by jonmeredith** [comment]
+1 37ad44d

**Comment by cmeiklejohn** [comment]
@borshop merge

**Comment by jonmeredith** [comment]
Thinking a bit harder about this, I hadn't realized that the `riak_repl_bucket_type_util:property_hash` function was already around for realtime.

If we change the way the hash is generated, this is going to break realtime replication between mixed version clusters.

Lazy question - do we have any r_t's that validate matching configs work and bad configs are rejected during rolling upgrades?

**Comment by cmeiklejohn** [comment]
I'm reverting this commit and will re-open a version that introduces capabilities this week.

Additionally, to answer your question: no, we don't have those tests.

**Pull request merged**
