### PR TITLE
Update AAE fullsync to support bucket types

### PR DESCRIPTION
**Pull request by ian-mi**
Fixes issue #663 (RIAK-1292) (RIAK-1294) (RIAK-1295) by updating `encode_obj_msg` to support the `w2` wire protocol, and by changing the AAE sink to use an updated `decode_obj_msg` function which can now properly handle bucket type property hashes.

`encode_obj_msg` and `decode_obj_msg` are not currently proper inverses of each other, but I kept the current behavior as not all messages passed to `decode_obj_msg` are guaranteed to be encoded using `encode_obj_msg`.

I have manually verified that this allows keys with a bucket type to be synced using AAE fullsync, but a test combining bucket types and AAE fullsync should probably be added to `riak_test`.

### CODE REVIEW

**Comment by bsparrow435** [comment]
Code looks good. Will add a test for this tomorrow to riak_test and then we can merge.

**Comment by bsparrow435** [comment]
Still in progress, riak_test setup has taken longer than anticipated. Will update again today.

**Comment by bsparrow435** [comment]
Test finished, fails as expected with current code but am also getting failure with this branch. Investigating more now.

**Comment by bsparrow435** [comment]
riak_test PR: https://github.com/basho/riak_test/pull/770

Fails without this change, passes with the change.

:+1: for merge

**Comment by bsparrow435** [comment]
@borshop :+1: bffb7dfbb4a5a5c4c2784846f94e3488b57f7810

**Comment by bsparrow435** [comment]
+1 bffb7dfbb4a5a5c4c2784846f94e3488b57f7810

**Comment by bsparrow435** [comment]
:+1: bffb7dfbb4a5a5c4c2784846f94e3488b57f7810

**Comment by bsparrow435** [comment]
@borshop retry

**Comment by bsparrow435** [comment]
@borshop: retry

**Comment by bsparrow435** [comment]
@borshop :retry

**Comment by bsparrow435** [comment]
+1 bffb7dfbb4a5a5c4c2784846f94e3488b57f7810

**Comment by bsparrow435** [comment]
@borshop merge

**Comment by bsparrow435** [comment]
@borshop why have you forsaken me?

**Comment by fadushin** [comment]
Retry needs to be on the branch, not on the PR, I think.

**Comment by bsparrow435** [comment]
@jonmeredith or @lordnull i'm told by others that this needs a review from one of you all before we can re-merge. Test is basho/riak_test#770

enjoy.

**Comment by bsparrow435** [comment]
Ping @jonmeredith or @lordnull . I've been told by leads that I do not have review rights so one of you needs to review this.

**Comment by lordnull** [comment]
This particular pr has been merged, so to get it in again a new pr will need to be opened. github can't re-open merged pr's unfortunately.

Since it's been merged once, it'll likely be an easy review.

**Comment by jonmeredith** [comment]
@bsparrow435 hey - did this ever get re-opened? I'm assuming it should be fixed on 2.0.6 and 2.next ?

**Comment by bsparrow435** [comment]
I'm on vacation, @ian-mi will need to re-open. Just make a new branch Ian with these changes so we can re-merge the re-merge before reverting and then re-merging :).

**Comment by jonmeredith** [comment]
A magical dance.   Sorry, didn't realize you were out - enjoy.

**Comment by cmeiklejohn** [comment]
@ian-mi Will there be a new PR opened for this that I can review?

**Comment by cmeiklejohn** [comment]
@ian-mi @bsparrow435 Will there be a new PR for this today against develop?

**Comment by bsparrow435** [comment]
Yes, Ian is working on this now. Git is complaining about his revert of the revert so he may just need to make a fresh branch and just copy/paste the changes.

**Comment by jonmeredith** [comment]
Although this is reverted and we're looking for a more general solution to replicated bucket properties, I wanted to add a note here in case we use something like this in the interim.

I can definitely see why it's logically sound to put the decoding stuff into riak_repl_util, but that means that the objects will travel between the aae_sink and the worker process as decoded objects rather than as binaries and I'm concerned this will cause a minor performance regressions - generating more garbage on the aae_sink process and increased term copying.

**Comment by ian-mi** [comment]
Thank you for the feedback. I went with the current implementation as it was the simplest and I wanted to minimize changes to the way the code is currently structured. I can investigate modifying this PR to do all decoding in the worker process if you don't already have an alternative solution in mind. I agree we should eventually unify the handling of replicated bucket properties between realtime and both fullsync methods with a more general solution.

**Pull request merged**
