### PR TITLE
Add sink cluster name to fullsync completion message

### PR DESCRIPTION
**Pull request by buddhisthead**
This PR adds the name of the sink cluster to the info log message for when a full sync completes. This is very handy when debugging/monitoring the completion of fullsyncs when more than one fullsync may be running concurrently.

Pretty trivial change to a lager:info() call. Tested.

The old message:
`2013-06-11 18:29:49.705 [info] <0.2992.0>@riak_repl2_fscoordinator:handle_info:362 Fullsync complete`

The new message:
`2013-06-11 18:29:49.705 [info] <0.2992.0>@riak_repl2_fscoordinator:handle_info:362 Fullsync complete to "B"`

### CODE REVIEW

**Comment by bookshelfdave** [comment]
+1, tested with a fullsync

would it be worth adding the source cluster name to help out with anyone reading the logs out of context?

**Comment by buddhisthead** [comment]
@metadave, Thanks for the review. That would be cool, except we don't have that information handy. They just have to know which cluster they are running for now. We can add the source cluster name when we address the issue with proper stats.

**Comment by buddhisthead** [comment]
Well, you motivated me to find a way... let me test it first.

```
MyClusterName = riak_core_connection:symbolic_clustername(),
lager:info("Fullsync complete from ~s to ~s",
                [MyClusterName, State#state.other_cluster]),
```

**Comment by buddhisthead** [comment]
Ok, added source name as well. And used ~s formatting to remove quotes.
Now, we have...

`[info] <0.27983.0>@riak_repl2_fscoordinator:handle_info:363 Fullsync complete from A to B`

**Comment by bookshelfdave** [comment]
looks good:

```
2013-06-12 17:04:18.506 [info] <0.10231.0>@riak_repl2_fscoordinator:handle_info:363 Fullsync complete from foo to bar
```

:+1:

**Comment by buddhisthead** [comment]
Thanks for the re-check, @metadave

**Pull request merged**
